# Override file for development specific settings
version: '3.8'

services:
  postgres:
    # Mount local folder for database scripts
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    # Enable logging for development
    command: >
      postgres
      -c logging_collector=on
      -c log_destination=stderr
      -c log_statement=all
      -c log_duration=on
      -c log_min_duration_statement=0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weekly_report_dev
      # Enable detailed logging
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
