# fly.toml app configuration file for weekly-report-backend
app = "weekly-report-backend"
primary_region = "sin"

[build]

[env]
  NODE_ENV = "production"
  PORT = "8080"
  # Add Node.js crypto support
  NODE_OPTIONS = "--experimental-global-webcrypto"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1
  
  # Keep-alive settings for 24/7 operation
  keep_alive_timeout = "300s"
  
  # Optimized concurrency for performance CPU
  concurrency = { type = "connections", hard_limit = 500, soft_limit = 300 }

# Health checks with appropriate timeouts for performance CPU
[[http_service.checks]]
  interval = "30s"
  grace_period = "120s"
  method = "GET"
  path = "/health"
  protocol = "http"
  timeout = "25s"
  tls_skip_verify = false
  headers = { "User-Agent" = "fly-health-check" }

[[http_service.checks]]
  interval = "60s"
  grace_period = "180s"
  method = "GET"
  path = "/api/health"
  protocol = "http"
  timeout = "35s"
  tls_skip_verify = false
  headers = { "User-Agent" = "fly-health-check" }

# Performance CPU with 2GB RAM for 24/7 operation
[[vm]]
  memory = "2048MiB"
  cpu_kind = "performance"
  cpus = 1

# Deploy settings
[deploy]
  strategy = "immediate"
  max_concurrent_machines = 1