# fly.toml app configuration file for weekly-report-backend
# FIXED: Strict 24/7 configuration to prevent auto-sleep

app = "weekly-report-backend"
primary_region = "sin"

[build]

[env]
  NODE_ENV = "production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  
  # CRITICAL: Prevent auto-sleep completely
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1
  
  # Keep-alive settings
  keep_alive_timeout = "120s"
  
  # Optimized concurrency
  concurrency = { type = "connections", hard_limit = 300, soft_limit = 200 }

# Aggressive health checks to keep machine awake
[[http_service.checks]]
  interval = "10s"
  grace_period = "15s"
  method = "GET"
  path = "/health"
  protocol = "http"
  timeout = "10s"
  tls_skip_verify = false
  headers = { "User-Agent" = "fly-health-check" }

[[http_service.checks]]
  interval = "30s"
  grace_period = "20s"
  method = "GET"
  path = "/api/health"
  protocol = "http"
  timeout = "15s"
  tls_skip_verify = false
  headers = { "User-Agent" = "fly-health-check" }

# VM configuration - cost optimized but always-on
[[vm]]
  memory = "512mb"
  cpu_kind = "dedicated"
  cpus = 2

# Deploy settings - ensure single machine
[deploy]
  strategy = "immediate"
  max_concurrent_machines = 1
